{
	"next_topic_id": 2,
	"topic": [
		{
			"topic_id": 1,
			"title": "打开zeronet首页出现报错",
			"body": "现在打开zeronet首页会出现报错。\nInternal error: ValueError: Invalid control character at: line 4886 column 20 (char 352129)\nUiWebsocket.py line 78 > UiWebsocket.py line 247 > UiWebsocket.py line 733 > SiteManagerPlugin.py line 20 > MergerSitePlugin.py line 338 > SiteManager.py line 36 > __init__.py line 291 > __init__.py line 339 > decoder.py line 364 > decoder.py line 380\n看起来是python的问题，但却不知道如何处理，谁能帮帮我。",
			"added": 1497188642,
			"parent_topic_uri": "8_1NV87VmSkezRyz8NbFpdkYJsJUSfXx7LJa"
		}
	],
	"topic_vote": {},
	"next_comment_id": 2,
	"comment": {
		"1_1883MvxJCZEco6eo3zLvKZCpQB9WN8QCjN": [
			{
				"comment_id": 1,
				"body": "没有用btsync，用的是开源的syncthing。btsync试过，感觉有的功能不方便。",
				"added": 1498061832
			}
		]
	},
	"comment_vote": {}
}