{
	"next_topic_id": 2,
	"topic": [
		{
			"topic_id": 1,
			"title": "声明：我按照教程过程尝试新建站点时遇到问题，源身份yuzu丢失",
			"body": "教程地址：\nhttp://127.0.0.1:43110/19s3YNNMjrtLHcwsbwrq4aGfkhGokNDSAA/?Post:3:%E4%B8%AD%E6%96%87%E7%AB%99%E7%82%B9%E5%BC%80%E5%8F%91%E6%95%99%E7%A8%8B\n\n尝试以debug模式启动ZeroNet时，python2.7.13提示找不到模块。我在pip安装了那个模块后，再次尝试以debug模式启动，但还是提示找不到模块，之后我通过双击ZeroNet.exe启动ZeroNet，发现数据库重置，身份信息已经丢失。",
			"added": 1487235815,
			"parent_topic_uri": "8_1NV87VmSkezRyz8NbFpdkYJsJUSfXx7LJa"
		}
	],
	"topic_vote": {},
	"next_comment_id": 2,
	"comment": {
		"1_1DW6mqHujWtzWDMrodReL6GdavkBnuCcjd": [
			{
				"comment_id": 1,
				"body": "> [linker](#comment_24_1PK7r15RmMdmdnUCYeQEwuydfediNVDtt2): ZeroNet.exe的data文件夹和你直接运行zeronet.py所用的data文件夹并不在同样的位置。建议你全盘搜索 users.json 看看有几个？\n\n有4个，分别在\nZeroNet\\data\nZeroNet\\core\\data\nZeroNet\\core\\data\\1iD5ZQJMNXu43w1qLB8sfdHVKppVMduGz\\data\nZeroNet\\core\\data\\1UDbADib99KE9d3qZ87NqJF2QLTHmMkoV\\data\\userdb",
				"added": 1487238475
			}
		]
	},
	"comment_vote": {}
}